version: '3.8'

services:
  simisai:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CV_MODEL_PATH=cv_model/models/poc2/best.pt
      # Add other environment variables as needed
      # - DATABASE_URL=your_database_url_here
      # - SEALION_API_KEY=your_sealion_api_key_here
      # - SEALION_API_URL=your_sealion_api_url_here
      # - SESSION_SECRET=your_session_secret_here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/cv/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
